### ISSUE TITLE
看了你的项目 有个问题 

### ISSUE THREAD

**Issue by qrh672114236** [WangJie0822/SampleProject#1]
viewmodel 我看你是用koin动态注入的形式生成的对象，但是动态注入的对象 没有自动调用 官方的 ViewModelProviders.of(this) 的方法 也就是你生成的viewmodel对象其实根本没有绑定对应UI的生命周期 我可以这样理解吗？ 刚学习jetpack 如果说的不对 希望可以指导

**Comment by WangJie0822** [comment]
并不是，你可以看看koin的源码，内部实现实际还是用了Jetpeck的实现
